"""Rollout Routing Replay (R3) for Megatron-Core MoE routers.

During RL training, the trainer re-runs forward passes over sequences that were
generated by the rollout engine (SGLang). For MoE models, tiny numerical
differences between the rollout and training stacks can flip top-k routing
decisions, which makes the training-time logprobs diverge from the rollout-time
ones. R3 removes this divergence by replaying the *recorded* rollout routing
decisions inside the trainer's routers.

This module provides:

- :class:`RoutingReplayContext` — a stage machine (``OFF`` / ``RECORD`` /
  ``REPLAY_FORWARD`` / ``REPLAY_BACKWARD``) holding per-layer FIFO queues of
  recorded top-k expert indices with *separate* forward and backward cursors.
  Activation recomputation re-runs layer forwards during the backward pass, so
  the same per-layer sequence must be served twice; the backward cursors serve
  the second pass without disturbing the forward bookkeeping.
- :func:`install_topk_router_patch` — a monkeypatch of
  ``megatron.core.transformer.moe.router.TopKRouter.forward`` (megatron-core
  0.13.1 has no native routing-forcing hook). When the active context is armed,
  the patched forward looks up the recorded top-k indices for the layer, builds
  a boolean ``routing_map`` and computes
  ``probs = softmax(logits.masked_fill(~routing_map, -inf))`` in fp32 — the
  masked softmax is mathematically identical to top-k renormalization (HF
  ``norm_topk_prob=True``) and stays differentiable through the router weight.
- :func:`assert_router_config_supported` — the replay path only reproduces
  megatron's ``topk_softmax_with_capacity`` for one specific router
  configuration; every other configuration is rejected at init instead of
  silently training with different gate weights than the rollout used.

Megatron imports are lazy so this module can be used (and unit-tested) in
environments without megatron-core / TransformerEngine installed.

Expert ids are LOGICAL (``0..num_experts-1``), matching both the HF layer
numbering and SGLang's capture point (pre-EPLB remap).

Install / consume lockstep
--------------------------
The correctness of the FIFO queues rests on one invariant:

    records for megatron layer ``L`` are appended only by forwards that also
    consume ``L``, in the same ``forward_step``.

That is what makes "the forward queue is exhausted" a reliable signal that a
fetch is an activation-recompute re-forward. Records are therefore installed
**per model chunk** (see :meth:`RoutingReplayContext.install_packed`'s
``chunk_index``): under virtual pipeline parallelism megatron forwards the same
micro-batch dict once per model chunk, and installing every local layer on
chunk 0's forward would make the queues of layers hosted on chunks >= 1 run
ahead of their own forwards — silently serving a later micro-batch's rows to a
recompute and an earlier one to a genuine forward. :meth:`fetch` additionally
*checks* the invariant on every replayed forward, so any future violation fails
loudly instead of corrupting training.

Record lifetime and dtype
-------------------------
Records are the rollout capture's own int16 rows, stored as the strided view
:meth:`install_packed` slices out of the micro-batch's ``[tokens,
num_moe_layers, top_k]`` tensor. They are never widened or copied on the way
in: int64 is needed only as a ``scatter_`` index, only for the one layer being
served, so :meth:`fetch` materializes that as a per-call transient. Storing
``.long()`` instead cost a resident 4x contiguous copy per layer per
micro-batch (48 layers x top-8 x 8 B = 3072 B/token against 768 B/token at the
source).

A pass also releases what it is done with: :meth:`fetch` drops the reference to
every record slot that no cursor can legally read again (the slot is set to
``None``, never removed, so record indices, the lockstep check and
:meth:`assert_all_consumed` keep seeing the full history). Without that, a
forward-only pass over a whole DP-rank batch — hundreds of micro-batches for
the prox/ref logp passes — kept every micro-batch's routing resident for the
whole ``forward_backward_func`` invocation, against a live need of one.

TODO(agent): the recompute re-forward is still *inferred* (the layer's forward
queue is exhausted) rather than announced. The lockstep check above makes that
inference verifiable rather than merely plausible, and the whole schedule is
simulated on CPU in ``tests/test_routing_replay_vpp_schedule.py``, but the
complete fix is an explicit signal from the recompute site: wrap megatron's
``checkpoint``/``CheckpointFunction`` re-forward so it flips the context into
``ReplayStage.REPLAY_BACKWARD`` for its duration (which would also retire the
``auto_backward`` fall-through). Until then the per-chunk + PP/VPP behavior has
only been validated against the simulated schedule, never on real GPUs.
"""

import enum
from collections.abc import Sequence
from typing import Any

import torch

_SUPPORTED_MEGATRON_CORE_VERSION = "0.13.1"

# Attribute stamped on each megatron model chunk so that its own forward
# installs only the routing records for the layers that chunk hosts.
_CHUNK_INDEX_ATTR = "_astraflow_replay_chunk_index"


class RoutingReplayError(RuntimeError):
    """Raised on any routing-replay bookkeeping violation (fail-fast)."""


class ReplayStage(enum.Enum):
    """Stage of the routing replay state machine."""

    OFF = "off"
    RECORD = "record"
    REPLAY_FORWARD = "replay_forward"
    REPLAY_BACKWARD = "replay_backward"


class RoutingReplayContext:
    """Per-layer routed-expert records with forward/backward cursor discipline.

    Args:
        layer_map: Single-chunk convenience form of ``chunk_layer_maps``. Maps a
            megatron ``layer_number`` (1-based, global across PP/VPP stages —
            ``TransformerLayer.layer_number`` already includes the stage offset)
            to the index along the MoE-layer axis of the packed
            ``routed_experts`` tensor (i.e. the global MoE layer ordinal in HF
            layer order). Only layers present in the map are installed and
            validated, which keeps the context PP-safe.
        chunk_layer_maps: One such map per local megatron model chunk, in
            ``model`` order. Required under virtual pipeline parallelism, where
            each chunk must install (and consume) only its own layers. Mutually
            exclusive with ``layer_map``.
        num_moe_layers: Total number of MoE layers the rollout tensor is
            expected to carry. When given, :meth:`install_packed` requires an
            exact match instead of merely "enough" layers, so a rollout tensor
            captured from a different model cannot silently be used as a prefix.
        owner: Human-readable identity of the engine that owns this context,
            used by :func:`set_replay_context` to report ownership conflicts.
    """

    def __init__(
        self,
        layer_map: dict[int, int] | None = None,
        *,
        chunk_layer_maps: Sequence[dict[int, int]] | None = None,
        num_moe_layers: int | None = None,
        owner: str | None = None,
    ):
        if layer_map is not None and chunk_layer_maps is not None:
            raise RoutingReplayError(
                "Pass either layer_map (single chunk) or chunk_layer_maps (one "
                "per megatron model chunk), not both."
            )
        if chunk_layer_maps is not None:
            self.chunk_layer_maps: list[dict[int, int]] | None = [
                dict(chunk_map) for chunk_map in chunk_layer_maps
            ]
            merged: dict[int, int] = {}
            for chunk_index, chunk_map in enumerate(self.chunk_layer_maps):
                for layer_number in chunk_map:
                    if layer_number in merged:
                        raise RoutingReplayError(
                            f"Megatron layer {layer_number} appears in more than "
                            f"one model chunk layer map (chunk {chunk_index}); "
                            "chunk layer maps must be disjoint."
                        )
                merged.update(chunk_map)
            self.layer_map: dict[int, int] | None = merged
        elif layer_map is not None:
            self.layer_map = dict(layer_map)
            self.chunk_layer_maps = [dict(layer_map)]
        else:
            self.layer_map = None
            self.chunk_layer_maps = None
        self.num_moe_layers = num_moe_layers
        self.owner = owner
        self._stage = ReplayStage.OFF
        self._auto_backward = False
        self._lockstep = False
        # Consumed slots are set to None (see _release_consumed), never
        # removed: the list length and the record indices are load-bearing for
        # the lockstep check, the double-consume check and assert_all_consumed.
        self._records: dict[int, list[torch.Tensor | None]] = {}
        self._forward_cursors: dict[int, int] = {}
        self._backward_cursors: dict[int, int] = {}
        # Per layer, how many leading record slots have already been released.
        self._released: dict[int, int] = {}

    @property
    def stage(self) -> ReplayStage:
        return self._stage

    @property
    def num_chunks(self) -> int:
        """Number of megatron model chunks this context was built for."""
        return len(self.chunk_layer_maps) if self.chunk_layer_maps is not None else 0

    @property
    def is_armed(self) -> bool:
        """Whether the router patch should serve recorded routings."""
        return self._stage in (ReplayStage.REPLAY_FORWARD, ReplayStage.REPLAY_BACKWARD)

    def reset(self) -> None:
        """Drop all records and cursors (stage is left untouched)."""
        self._records.clear()
        self._forward_cursors.clear()
        self._backward_cursors.clear()
        self._released.clear()

    def set_stage(self, stage: ReplayStage, auto_backward: bool = False) -> None:
        """Set the stage manually (debug / unit-test entry point).

        Manual staging disables the install/consume lockstep check, since
        records may have been appended by hand via :meth:`record` rather than
        one-per-forward via :meth:`install_packed`. Production passes go through
        :meth:`begin_pass`.

        Args:
            stage: The new stage.
            auto_backward: Only meaningful for ``REPLAY_FORWARD``. When True, a
                fetch that finds its per-layer forward queue exhausted is
                served from the backward cursor instead of raising. This is
                how activation-recompute re-forwards are served in the real
                Megatron schedule: records are installed immediately before
                each micro-batch's forward, so at the time a recompute re-runs
                a layer its forward queue is always fully consumed.
        """
        self._stage = stage
        self._auto_backward = stage is ReplayStage.REPLAY_FORWARD and auto_backward
        self._lockstep = False

    def begin_pass(self, forward_only: bool) -> None:
        """Arm the context for one ``forward_backward_func`` invocation."""
        self.reset()
        self.set_stage(ReplayStage.REPLAY_FORWARD, auto_backward=not forward_only)
        # Production passes install exactly one chunk per layer immediately
        # before that layer's forward, so fetch() can (and must) verify it.
        self._lockstep = True

    def end_pass(self) -> None:
        """Disarm the context and drop the pass's records."""
        self.reset()
        self.set_stage(ReplayStage.OFF)

    def record(self, layer_number: int, topk_ids: torch.Tensor) -> None:
        """Append one recorded chunk of top-k ids ``[tokens, top_k]`` for a layer.

        The tensor is stored **as it arrives** — same dtype (the rollout
        capture is int16), same strided view of the caller's packed tensor. The
        int64 widening that ``scatter_`` needs happens per fetch, on the one
        chunk being served; doing it here made every micro-batch of the pass
        carry a resident 4x contiguous copy per layer.
        """
        if topk_ids.dim() != 2:
            raise RoutingReplayError(
                f"Expected [tokens, top_k] indices for layer {layer_number}, "
                f"got shape {tuple(topk_ids.shape)}."
            )
        self._records.setdefault(layer_number, []).append(topk_ids.detach())
        self._forward_cursors.setdefault(layer_number, 0)
        self._backward_cursors.setdefault(layer_number, 0)
        self._released.setdefault(layer_number, 0)

    def _chunk_layer_map(self, chunk_index: int | None) -> dict[int, int]:
        if self.chunk_layer_maps is None:
            raise RoutingReplayError(
                "install_packed requires a layer_map mapping megatron layer "
                "numbers to MoE layer indices."
            )
        if chunk_index is None:
            if len(self.chunk_layer_maps) != 1:
                raise RoutingReplayError(
                    "install_packed must name the megatron model chunk it is "
                    f"installing for: this context spans {len(self.chunk_layer_maps)} "
                    "chunks (virtual pipeline parallelism). Installing every "
                    "layer on one chunk's forward breaks the install/consume "
                    "lockstep and silently serves the wrong micro-batch's rows."
                )
            return self.chunk_layer_maps[0]
        if not 0 <= chunk_index < len(self.chunk_layer_maps):
            raise RoutingReplayError(
                f"Model chunk index {chunk_index} is out of range for a context "
                f"built for {len(self.chunk_layer_maps)} chunk(s)."
            )
        return self.chunk_layer_maps[chunk_index]

    def install_packed(
        self, routed_experts: torch.Tensor, chunk_index: int | None = None
    ) -> None:
        """Install one micro-batch of packed routed experts for one model chunk.

        Args:
            routed_experts: ``[tokens, num_moe_layers, top_k]`` integer tensor
                whose token axis has already been sliced down to what this
                rank's routers will see (CP zigzag split and, under sequence
                parallelism, the local contiguous SP chunk).
            chunk_index: Index of the megatron model chunk whose forward is
                about to run. Only the layers hosted on that chunk are
                installed, which is what keeps install and consume in lockstep
                under virtual pipeline parallelism. May be omitted only when
                the context spans a single chunk.
        """
        layer_map = self._chunk_layer_map(chunk_index)
        if routed_experts.dim() != 3:
            raise RoutingReplayError(
                "Expected routed_experts of shape [tokens, num_moe_layers, top_k], "
                f"got shape {tuple(routed_experts.shape)}."
            )
        num_moe_layers = routed_experts.shape[1]
        if self.num_moe_layers is not None and num_moe_layers != self.num_moe_layers:
            raise RoutingReplayError(
                f"routed_experts carries {num_moe_layers} MoE layers, but this "
                f"model has {self.num_moe_layers}. The rollout capture and the "
                "trainer disagree about the model; refusing to use a prefix."
            )
        for layer_number, moe_index in layer_map.items():
            if moe_index >= num_moe_layers:
                raise RoutingReplayError(
                    f"Layer {layer_number} maps to MoE index {moe_index}, but the "
                    f"routed_experts tensor only has {num_moe_layers} MoE layers."
                )
            self.record(layer_number, routed_experts[:, moe_index, :])

    def fetch(self, layer_number: int, num_rows: int) -> torch.Tensor:
        """Serve the next recorded chunk for ``layer_number`` as int64 ids.

        Consumption follows the stage machine: ``REPLAY_FORWARD`` serves from
        the forward cursor (falling through to the backward cursor when
        ``auto_backward`` was requested and the forward queue is exhausted —
        that is an activation-recompute re-forward); ``REPLAY_BACKWARD`` serves
        strictly from the backward cursor. Serving the same chunk a third time
        (or fetching with no record available) raises
        :class:`RoutingReplayError`.

        In a production pass (armed via :meth:`begin_pass`) the install/consume
        lockstep is verified: a genuine forward must consume exactly the chunk
        that its own ``forward_step`` just installed, i.e. the forward cursor
        must sit on the last record. A forward cursor that lags further behind
        means records were appended by a forward that does not consume this
        layer, which would silently serve the wrong micro-batch's rows.

        The returned int64 tensor is a per-call transient: the record itself
        keeps the rollout's own (int16) dtype, and is released as soon as no
        cursor can read it again — see :meth:`_release_consumed`.
        """
        records = self._records.get(layer_number)
        if not records:
            raise RoutingReplayError(
                f"No recorded routing available for megatron layer {layer_number}. "
                "Was 'routed_experts' installed for this micro-batch?"
            )
        if self._stage is ReplayStage.REPLAY_FORWARD:
            cursor_name = "forward"
            cursors = self._forward_cursors
            if cursors[layer_number] >= len(records):
                if self._auto_backward:
                    cursor_name = "backward"
                    cursors = self._backward_cursors
            elif self._lockstep and cursors[layer_number] != len(records) - 1:
                raise RoutingReplayError(
                    "Routing replay install/consume lockstep violated on megatron "
                    f"layer {layer_number}: forward cursor is at "
                    f"{cursors[layer_number]} but {len(records)} chunks have been "
                    "installed. Records for a layer must be appended only by the "
                    "forward that consumes them (one per forward_step); a queue "
                    "that runs ahead means some other model chunk's forward "
                    "installed this layer, and the fetch would return a different "
                    "micro-batch's routing. Check that every model chunk installs "
                    "only its own layers (see install_packed(chunk_index=...))."
                )
        elif self._stage is ReplayStage.REPLAY_BACKWARD:
            cursor_name = "backward"
            cursors = self._backward_cursors
        else:
            raise RoutingReplayError(
                f"fetch() called while the context stage is {self._stage.value}."
            )
        cursor = cursors[layer_number]
        if cursor >= len(records):
            raise RoutingReplayError(
                f"Routing record double-consume on megatron layer {layer_number}: "
                f"{cursor_name} cursor already consumed all {len(records)} chunks."
            )
        chunk = records[cursor]
        if chunk is None:
            raise RoutingReplayError(
                f"Routing record for megatron layer {layer_number} chunk {cursor} "
                f"was released before the {cursor_name} pass read it. A chunk is "
                "only released once every cursor that may still read it has moved "
                "past it, so this means the release condition and the consume "
                "order disagree."
            )
        if chunk.shape[0] != num_rows:
            raise RoutingReplayError(
                f"Recorded routing rows ({chunk.shape[0]}) do not match router "
                f"logits rows ({num_rows}) on megatron layer {layer_number} "
                f"(chunk {cursor}, {cursor_name} pass)."
            )
        cursors[layer_number] = cursor + 1
        # int64 lives only here: torch requires an int64 scatter_ index, but
        # only for the layer currently being served. Widening the record itself
        # would keep that 4x copy resident for the whole pass.
        topk_ids = chunk.long()
        self._release_consumed(layer_number, records)
        return topk_ids

    def _no_backward_replay_possible(self) -> bool:
        """Whether nothing can read this pass's records a second time.

        True only for a production pass armed by
        ``begin_pass(forward_only=True)``: it sets the lockstep flag and leaves
        ``auto_backward`` off, and megatron's ``forward_only=True`` schedule
        issues no backward and therefore no activation-recompute re-forward.

        A manually staged context (:meth:`set_stage`, which clears the lockstep
        flag) never qualifies, because the caller may flip it into
        ``REPLAY_BACKWARD`` afterwards to serve the same chunks again; neither
        does ``auto_backward``, whose whole purpose is that second read.
        """
        return (
            self._lockstep
            and not self._auto_backward
            and self._stage is ReplayStage.REPLAY_FORWARD
        )

    def _release_consumed(
        self, layer_number: int, records: list[torch.Tensor | None]
    ) -> None:
        """Drop references to records no cursor can legally read again.

        A chunk is dead once the forward cursor is past it *and* — unless a
        backward replay is provably impossible for this pass — the backward
        cursor is past it too. Cursors only ever move forward within a pass and
        :meth:`reset` clears records and cursors together, so a chunk behind
        both cursors can never be served again.

        Slots are nulled in place rather than popped: :meth:`fetch` indexes
        ``records`` by cursor, the lockstep check compares the cursor against
        ``len(records) - 1``, and :meth:`assert_all_consumed` compares cursors
        against ``len(records)``. All three keep seeing the full history.
        """
        limit = self._forward_cursors.get(layer_number, 0)
        if not self._no_backward_replay_possible():
            limit = min(limit, self._backward_cursors.get(layer_number, 0))
        released = self._released.get(layer_number, 0)
        if limit <= released:
            return
        for index in range(released, limit):
            records[index] = None
        self._released[layer_number] = limit

    def assert_all_consumed(
        self, require_backward: bool = False, require_records: bool = False
    ) -> None:
        """Validate that every recorded chunk was consumed exactly once per pass.

        The forward cursor of every recorded layer must have consumed all of
        its chunks. Backward consumption is all-or-nothing per layer: either
        the layer was never re-forwarded (no activation recompute) or all of
        its chunks were served again. With ``require_backward=True`` a full
        backward replay is mandatory.

        With ``require_records=True`` the pass must also have installed records
        for every layer in :attr:`layer_map`. Without it an entirely inactive
        context (e.g. one that was never installed as the process-wide active
        context, so the routers free-ran) passes vacuously.
        """
        problems = []
        if require_records:
            expected = set(self.layer_map or {})
            missing = sorted(expected - set(self._records))
            if missing:
                problems.append(
                    f"layers {missing} recorded nothing at all (the replay context "
                    "was never consulted by the routers: is it the process-wide "
                    "active context, and does every micro-batch carry "
                    "'routed_experts'?)"
                )
        for layer_number, records in self._records.items():
            num_chunks = len(records)
            fwd = self._forward_cursors.get(layer_number, 0)
            bwd = self._backward_cursors.get(layer_number, 0)
            if fwd != num_chunks:
                problems.append(
                    f"layer {layer_number}: forward consumed {fwd}/{num_chunks}"
                )
            if require_backward:
                if bwd != num_chunks:
                    problems.append(
                        f"layer {layer_number}: backward consumed {bwd}/{num_chunks}"
                    )
            elif bwd not in (0, num_chunks):
                problems.append(
                    f"layer {layer_number}: backward partially consumed "
                    f"{bwd}/{num_chunks}"
                )
        if problems:
            raise RoutingReplayError(
                "Routing replay records were not consumed exactly once per pass: "
                + "; ".join(problems)
            )


# NOTE: a plain module global, NOT threading.local — activation-recompute
# re-forwards run on the autograd engine's worker thread, which must observe
# the same context as the main thread that armed it.
_REPLAY_CONTEXT: RoutingReplayContext | None = None


def set_replay_context(context: RoutingReplayContext | None) -> None:
    """Install (or clear, with None) the process-wide active replay context.

    The active context is process-wide, but a training process builds several
    engines in sequence (actor, optional critic, optional ref). Installing a
    second engine's context while another one is still installed used to
    silently win: the displaced engine's ``begin_pass`` armed a context nobody
    consulted, its routers free-ran, and ``assert_all_consumed`` iterated an
    empty record dict and passed vacuously. Overwriting a *different* installed
    context is therefore refused; engines install their context only for the
    duration of one ``forward_backward_func`` invocation and release it with
    :func:`release_replay_context`.
    """
    global _REPLAY_CONTEXT
    current = _REPLAY_CONTEXT
    if context is not None and current is not None and current is not context:
        raise RoutingReplayError(
            "Refusing to overwrite the active routing-replay context owned by "
            f"{current.owner!r} with the one owned by {context.owner!r}. The "
            "active context is process-wide, so two engines with "
            "megatron.moe_router_replay=True cannot be armed at the same time — "
            "the displaced engine's routers would silently free-run instead of "
            "replaying the rollout routing. Install the context only around a "
            "forward/backward pass (and release it afterwards), or disable "
            "moe_router_replay on one of the engines."
        )
    _REPLAY_CONTEXT = context


def release_replay_context(context: RoutingReplayContext | None) -> None:
    """Clear the active context, but only if ``context`` is the one installed."""
    global _REPLAY_CONTEXT
    if context is None or _REPLAY_CONTEXT is context:
        _REPLAY_CONTEXT = None


def get_replay_context() -> RoutingReplayContext | None:
    """Return the process-wide active replay context, if any."""
    return _REPLAY_CONTEXT


def set_replay_chunk_index(model_chunk: Any, chunk_index: int) -> None:
    """Stamp a megatron model chunk with its index in the local chunk list."""
    setattr(model_chunk, _CHUNK_INDEX_ATTR, chunk_index)


def get_replay_chunk_index(model_chunk: Any) -> int | None:
    """Return the chunk index stamped by :func:`set_replay_chunk_index`."""
    return getattr(model_chunk, _CHUNK_INDEX_ATTR, None)


def assert_router_config_supported(
    config: Any, layer_number: int | None = None
) -> None:
    """Reject router configurations the replay path does not reproduce.

    The replay path returns ``softmax(logits.masked_fill(~routing_map, -inf))``,
    which equals megatron's ``topk_softmax_with_capacity`` **only** for
    ``score_function='softmax'``, ``use_pre_softmax=False``, no
    ``scaling_factor`` and no expert capacity factor. mbridge configures
    ``moe_router_pre_softmax=True`` for qwen2moe and mixtral (their probs are
    gathered slices of the *full* softmax, deliberately not renormalized) and
    sigmoid + ``moe_router_topk_scaling_factor`` for deepseek_v3; replaying
    those would train with systematically larger gate weights than the rollout
    used while looking perfectly healthy. Qwen3-MoE (the supported family) gets
    ``score_function='softmax'``, ``pre_softmax=False`` and no scaling/capacity
    factor from ``mbridge.models.qwen3moe``.

    Settings whose bookkeeping the replay path deliberately skips (z-loss, aux
    loss, expert bias) are rejected too, rather than being silently dropped.
    """
    where = f" on megatron layer {layer_number}" if layer_number is not None else ""
    problems: list[str] = []

    score_function = getattr(config, "moe_router_score_function", "softmax")
    if score_function != "softmax":
        problems.append(
            f"moe_router_score_function={score_function!r} (replay implements the "
            "post-softmax top-k renormalization only)"
        )
    if getattr(config, "moe_router_pre_softmax", False):
        problems.append(
            "moe_router_pre_softmax=True (probs would be un-renormalized slices "
            "of the full softmax, not a renormalized top-k softmax)"
        )
    scaling_factor = getattr(config, "moe_router_topk_scaling_factor", None)
    if scaling_factor:
        problems.append(
            f"moe_router_topk_scaling_factor={scaling_factor} (replay does not "
            "scale the gate weights)"
        )
    capacity_factor = getattr(config, "moe_expert_capacity_factor", None)
    if capacity_factor is not None:
        problems.append(
            f"moe_expert_capacity_factor={capacity_factor} (replay never drops "
            "tokens, so the trainer would keep tokens the reference math drops)"
        )
    group_topk = getattr(config, "moe_router_group_topk", None)
    if group_topk:
        problems.append(
            f"moe_router_group_topk={group_topk} (group-limited routing is not "
            "reproduced by the replay path)"
        )
    if getattr(config, "moe_router_enable_expert_bias", False):
        problems.append(
            "moe_router_enable_expert_bias=True (replay skips the "
            "local_tokens_per_expert bookkeeping the bias update needs)"
        )
    if getattr(config, "moe_z_loss_coeff", None):
        problems.append(
            f"moe_z_loss_coeff={config.moe_z_loss_coeff} (replay skips z-loss)"
        )
    load_balancing_type = getattr(config, "moe_router_load_balancing_type", "none")
    aux_loss_coeff = getattr(config, "moe_aux_loss_coeff", 0.0)
    if load_balancing_type not in ("none",) and aux_loss_coeff:
        problems.append(
            f"moe_router_load_balancing_type={load_balancing_type!r} with "
            f"moe_aux_loss_coeff={aux_loss_coeff} (replay skips the auxiliary "
            "load-balancing loss; load balancing is meaningless under forced "
            "routing, so set moe_router_load_balancing_type='none')"
        )
    if getattr(config, "moe_router_force_load_balancing", False):
        problems.append(
            "moe_router_force_load_balancing=True (randomized routing logits are "
            "incompatible with replaying recorded routing)"
        )

    if problems:
        raise RoutingReplayError(
            f"Rollout routing replay does not support this router configuration"
            f"{where}: " + "; ".join(problems) + ". Disable megatron."
            "moe_router_replay for this model family."
        )


def routing_map_to_topk_indices(routing_map: torch.Tensor, topk: int) -> torch.Tensor:
    """Convert a boolean ``[tokens, num_experts]`` map to ``[tokens, topk]`` ids."""
    counts = routing_map.sum(dim=-1)
    if not torch.all(counts == topk):
        raise RoutingReplayError(
            f"routing_map rows must select exactly top_k={topk} experts, got "
            f"counts in [{int(counts.min())}, {int(counts.max())}]."
        )
    # nonzero() is row-major, so each row contributes its ids in ascending order.
    return routing_map.nonzero(as_tuple=True)[1].view(-1, topk)


def hf_moe_layer_indices(hf_config: Any) -> list[int]:
    """Global HF decoder-layer indices that host an MoE block.

    Mirrors HF ``Qwen3MoeDecoderLayer``: a layer is sparse iff it is not in
    ``mlp_only_layers``, the model has experts, and
    ``(layer_idx + 1) % decoder_sparse_step == 0``. For Qwen3-MoE checkpoints
    (empty ``mlp_only_layers``, ``decoder_sparse_step == 1``) this is every
    decoder layer.
    """
    num_layers = hf_config.num_hidden_layers
    mlp_only_layers = set(getattr(hf_config, "mlp_only_layers", None) or [])
    decoder_sparse_step = getattr(hf_config, "decoder_sparse_step", 1) or 1
    num_experts = getattr(hf_config, "num_experts", None)
    if num_experts is None:
        num_experts = getattr(hf_config, "num_local_experts", 0)
    return [
        layer_idx
        for layer_idx in range(num_layers)
        if layer_idx not in mlp_only_layers
        and num_experts > 0
        and (layer_idx + 1) % decoder_sparse_step == 0
    ]


def install_topk_router_patch() -> None:
    """Monkeypatch ``TopKRouter.forward`` to honor the active replay context.

    Idempotent. Pin-asserts megatron-core==0.13.1: the patched replay path
    re-implements the pre-``routing()`` part of ``TopKRouter.forward`` (jitter
    + gating), so any megatron upgrade must be re-verified by hand.

    Behavior by stage of the active context:

    - ``OFF`` (or no context): original forward, byte-identical behavior.
    - ``RECORD``: original forward, with the resulting top-k indices appended
      to the context (debug/validation path).
    - ``REPLAY_FORWARD`` / ``REPLAY_BACKWARD``: logits come from the real
      (differentiable) gating; the top-k *choice* is forced to the recorded
      indices and ``probs`` is the fp32 masked softmax over the chosen
      experts. Z-loss, aux-loss, and expert-bias bookkeeping are intentionally
      skipped — load balancing is meaningless under forced routing, and
      :func:`assert_router_config_supported` rejects configurations that would
      need them.
    """
    import megatron.core
    from megatron.core.transformer.moe.router import TopKRouter

    version = getattr(megatron.core, "__version__", None)
    if version != _SUPPORTED_MEGATRON_CORE_VERSION:
        raise RoutingReplayError(
            f"The TopKRouter routing-replay patch is pinned to megatron-core=="
            f"{_SUPPORTED_MEGATRON_CORE_VERSION}, found {version}. Re-verify the "
            "patched forward against the new router implementation before bumping."
        )
    if getattr(TopKRouter, "_astraflow_routing_replay_patched", False):
        return

    original_forward = TopKRouter.forward

    def forward(self, input: torch.Tensor):
        context = get_replay_context()
        if context is None or context.stage is ReplayStage.OFF:
            return original_forward(self, input)
        if context.stage is ReplayStage.RECORD:
            scores, routing_map = original_forward(self, input)
            context.record(
                self.layer_number, routing_map_to_topk_indices(routing_map, self.topk)
            )
            return scores, routing_map

        self._maintain_float32_expert_bias()
        logits = self.gating(self.apply_input_jitter(input))
        logits = logits.view(-1, self.config.num_moe_experts)
        topk_ids = context.fetch(self.layer_number, logits.shape[0])
        routing_map = torch.zeros_like(logits, dtype=torch.bool).scatter_(
            1, topk_ids.to(device=logits.device), True
        )
        probs = torch.softmax(
            logits.float().masked_fill(~routing_map, float("-inf")), dim=-1
        ).to(logits.dtype)
        return probs, routing_map

    TopKRouter.forward = forward
    TopKRouter._astraflow_routing_replay_patched = True
